<form id="addItemForm" method="post" enctype="multipart/form-data">
    <input name="id" type="hidden" class="form-control" id="inputItemId" placeholder="id">
    <div class="form-group row">
        <label for="inputItemName" class="col-sm-2 col-form-label">Название</label>
        <div class="col-sm-10">
            <input name="name" type="email" class="form-control" id="inputItemName" placeholder="Название">
        </div>
    </div>
    <div class="form-group row">
        <label for="inputItemPrice" class="col-sm-2 col-form-label">Цена</label>
        <div class="col-sm-10">
            <input name="price" type="text" class="form-control" id="inputItemPrice" placeholder="Цена">
        </div>
    </div>
    <div class="form-group row">
        <label for="inputItemDescr" class="col-sm-2 col-form-label">Описание</label>
        <div class="col-sm-10">
            <textarea name="descr" class="form-control" id="inputItemDescr" rows="3"></textarea>
        </div>
    </div>
    <div class="form-group row">
        <label for="inputItemImage" class="col-sm-4 col-form-label">Изображение</label>
        <div class="col-sm-8">
            <input name="img" type="file" class="form-control-file" id="inputItemImage">
        </div>
    </div>
</form>