<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Document</title>


    <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>

    <script src="http://malsup.github.com/jquery.form.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addItemModal" >Добавить</button>
            </li>
        </ul>
    </div>
</nav>

<main role="main" class="container">

    <div class="starter-template" style="margin-top: 80px;">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Название</th>
                <th scope="col">Цена</th>
                <th scope="col">Описание</th>
                <th scope="col">Изображение</th>
                <th scope="col">Кнопочки</th>
            </tr>
            </thead>
            <tbody id="itemsList">
            <? foreach ($items as $item) :?>
                <tr id="itemRow-<?= $item['id']?>">
                    <td><?= $item['id']?></td>
                    <td><?= $item['name']?></td>
                    <td><?= $item['price']?></td>
                    <td><?= $item['description']?></td>
                    <td><img src="<?= $item['img_url']?>"></td>
                    <td>
                        <button type="button" class="btn btn-primary btn-sm" onclick="editItem(<?= $item['id']; ?>)">Ред.</button>
                        <button type="button" class="btn btn-danger btn-sm" onclick="removeItem(<?= $item['id']; ?>)">Удалить</button>
                    </td>
                    <td></td>
                </tr>
            <? endforeach;?>
            </tbody>
        </table>
        <button id="addMore" type="button" class="btn btn-primary">Еще</button>
    </div>

</main><!-- /.container -->

<!-- Modal -->
<div class="modal fade" id="addItemModal" tabindex="-1" role="dialog" aria-labelledby="addItemModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addItemModalLabel">Добавить товар</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <?include 'addItemForm.phtml'?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="$('#addItemForm').clearForm()">Отмена</button>
                <button id="addItem" type="button" class="btn btn-primary">Добавить</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="editItemModal" tabindex="-1" role="dialog" aria-labelledby="editItemModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editItemModalLabel">Редактировать товар</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <?include 'addItemForm.phtml'?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="$('#addItemForm').clearForm()">Отмена</button>
                <button id="updateItem" type="button" class="btn btn-primary">Сохранить</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        var lastId = <?= end($items)['id']?>;
        $('#addMore').click(function() {
            $.get('/getList/'+lastId, {}, function(data) {
                data.forEach(function(item) {
                    $('#itemsList').append(
                        '<tr id="itemRow-'+item.id+'">' +
                            '<td>'+item.id+'</td>' +
                            '<td>'+item.name+'</td>' +
                            '<td>'+item.price+'</td>' +
                            '<td>'+item.description+'</td>' +
                            '<td><img src="'+item.price+'"></td>' +
                            '<td>' +
                                '<button type="button" class="btn btn-primary btn-sm">Ред.</button>'+
                                '<button type="button" class="btn btn-danger btn-sm" onclick="removeItem('+item.id+')">Удалить</button>'+
                            '</td>' +
                        '</tr>');
                    lastId = item.id;
                });
            })
        });

        $('#addItem').click(function() {
            $('#addItemForm').ajaxSubmit({url:'/addItem'}).clearForm();
        });

        $('#updateItem').click(function() {
            $('#editItemModal #addItemForm').ajaxSubmit({url:'/updateItem'}).clearForm();
        });


    });
    function removeItem(id) {
        $.get('/removeItem/'+id, {}, function(data) {
            if (data.result) {
                $('#itemRow-'+id).remove();
            }
        })
    }

    function editItem(id) {
        $.get('/getItem/'+id, {}, function(data) {
            if (data) {
                $('#editItemModal #inputItemId').val(data.id);
                $('#editItemModal #inputItemName').val(data.name);
                $('#editItemModal #inputItemPrice').val(data.price);
                $('#editItemModal #inputItemDescr').val(data.description);

                $('#editItemModal').modal();
            }
        })
    }


</script>
</body>
</html>